framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/utils/*.js"
    - "./test/*.js"
postMerge:
  pattern: 
    - "./test/utils/*.js"
    - "./test/*.js"
postRun:
     command:
        - yarn --version
        - yarn --version
version: 1.0


