framework: jest
preRun:
     command:
        - yarn install
preMerge:
  pattern:
    - "./test/**/*.js"
    - "./test/*.js"
postMerge:
  pattern: 
    - "./test/**/*.js"
    - "./test/*.js"
postRun:
     command:
        - yarn --version
version: 1.0
